---
bibliography: references.bib
---

# Introduction {#intro}

We create and apply molecular tools to control and understand human health and disease. We strive to quickly share our discoveries, combining contemporary methods of directed evolution and protein engineering with classic priciples of pharmacology and biochemsitry. 

See the next chapter for more detail on our lab culture and philosophy!

## How we meet

Currently, we meet in-person for weekly lab meetings on Thursdays and weekly individual meetings with Justin on Mondays.
We use a shared google calendar to schedule our meetings and keep up-to-date on meeting times and cancellations. 

## How we share things and give feedback

We use a web platform called [Basecamp](www.basecamp.com) to communicate and share project updates. All lab members will have access to our English Lab HQ page, where you can message the lab on the campfire chat or find helpful resources and protocols. Each lab member will also have a dedicated page for their individual projects, where they can take a project-based approach to organizing what they are working on in the To-Dos section. This makes it easier to share results and solicit feedback from others, as things tend to be self-contained and organized under a general project title. When sending updates to someone, whether via direct message (called a "ping") or on a to-do list, always make sure to describe what you are sending and try to make it as easy as possible for the person you are updating to help you.

Feedback, both giving and receiving it, is an important aspect of our lab. Most of the feedback we give and receive is when giving and attending practice talks. We expect feedback to be supportive but constructive.

This [resource from UBC](https://scwrl.ubc.ca/student-resources/learning-strategies-for-communicating-science/how-to-give-and-receive-effective-feedback/) does a really great job of outlining the main points of how to give and receive feedback.

## Shared lab resources

include in later section??

